spring.application.name=ms-ordenes-de-compra
server.port=8080

# Conexión Base de Datos Oracle
spring.datasource.url=jdbc:oracle:thin:@n2bf0ypy58fj8kam_tp?TNS_ADMIN=C:/Wallet/Wallet_N2BF0YPY58FJ8KAM
spring.datasource.username=ms_ordenes_compras
spring.datasource.password=ClaveEmpresa1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG

# Control de Errores
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# hikariCP 
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
logging.level.com.zaxxer.hikari=DEBUG